app:main.c utils.c
	gcc -o app main.c utils.c# 缩进错误
	gcc -o app main.c utils.c# 缩进错误
	gcc -o app main.c utils.c# 缩进错误
	gcc -o app main.c utils.c# 缩进错误
	gcc -o app main.c utils.c# 缩进错误
	gcc -o app main.c utils.c# 缩进错误
	gcc -o app main.c utils.c# 缩进错误
	gcc -o app main.c utils.c# 缩进错误
	gcc -o app main.c utils.c# 缩进错误
	gcc -o app main.c utils.c# 缩进错误
	gcc -o app main.c utils.c# 缩进错误
	gcc -o app main.c utils.c# 缩进错误
	gcc -o app main.c utils.c# 缩进错误
	gcc -o app main.c utils.c# 缩进错误